version: 2

updates:
- package-ecosystem: "npm"
  directory: "/web"
  schedule:
    interval: "daily"
    time: "09:00"
    timezone: "Asia/Shanghai"
  open-pull-requests-limit: 0
  target-branch: "main"
  assignees:
  - "EINDEX"
  labels:
  - "dependencies"

- package-ecosystem: "gomod"
  directory: "/api"
  schedule:
    interval: "daily"
    time: "09:00"
    timezone: "Asia/Shanghai"
  open-pull-requests-limit: 0
  target-branch: "main"
  assignees:
  - "EINDEX"
  labels:
  - "dependencies"
