baseURL = 'http://example.org/'
languageCode = 'cn'
title = 'My New Hugo Site'
theme = 'qingzhuo'


[markup]
  [markup.highlight]
    style='monokai'
    tabWidth=4

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true