
languageCode = 'cn'
theme = 'qingzhuo'
title = "EINDEX's Blog"

paginate = 7

hasCJKLanguage = true
summaryLength = 100

googleAnalytics = 'UA-80131414-1'
relativeURLS=true


[markup]
[markup.highlight]
style = 'monokai'
tabWidth = 4

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true


[outputs]
home = [ "RSS", "HTML"]

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"

[params]
baiduAnalytics = '73deedd5e22a061de8092928b65f7405'
microsoftClarity = 'ao1gr1m9ku'
outdateingWarningDays = 30
ICPNumbers = '鄂ICP备15018232号-1'

[params.giscus]
repo = "EINDEX/qingzhuo-hugo"
repoId = "R_kgDOGWb6Yg"
categoryId = "DIC_kwDOGWb6Ys4CAKn-"

[menu]
[[menu.navbar]]
identifier = "about"
name = "About Me"
url = "/about"
weight = -1

[[menu.navbar]]
name = "Archive"
url = "/"
weight = 0
