
languageCode = 'cn'
title = "QingZhuo Hugo theme"

# baseURL = "https://eindex.github.io/qingzhuo"

paginate = 10 # default page size

hasCJKLanguage = true # CJK support
summaryLength = 100 # default summary length

disableKinds = ['taxonomy', 'term']

[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'

## RSS support default open
[outputs]
home = [ "RSS", "HTML"]

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"

## menus in navbar
[menu]
[[menu.navbar]]
identifier = "about"
name = "About"
url = "/about/"
weight = -1

[[menu.navbar]]
name = "Archive"
url = "/archive/"
weight = -2


[params]
# Time to start show outdate warning, 0 to close.
outdateingWarningDays = 0

## Baidu Analytics
baiduAnalytics = ''

## Microsoft clarify
microsoftClarity = ''

## Google Analytics
googleAnalytics = ''

## ICP infomation China mainland only
ICPNumbers = ''

## BuSuanZi Visit Counter
BuSuanZi = false


## support type list: github, weibo, twitter, telegram, qq, wechat, website
## support link or value
[[params.socialaccount]]
link = 'https://github.com/eindex'
type = 'github'
[[params.socialaccount]]
link = 'https://twitter.com/eindex_li'
type = 'twitter'
[[params.socialaccount]]
link = 'https://t.me/eindex'
type = 'telegram'
[[params.socialaccount]]
link = 'mailto:eindex.me@outlook.com'
type = 'email'

## Giscus
[params.giscus]
repo = ""
repoId = ""
categoryId = ""


## Markup Configurations
[markup]

### Code Highlighting
[markup.highlight]
style = 'monokai'
tabWidth = 4

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

## hugo related logic
## https://gohugo.io/content-management/related/

[related]
  includeNewer = false
  threshold = 0
  toLower = false
[[related.indices]]
  name = 'tags'
  weight = 100
[[related.indices]]
  name = 'categories'
  weight = 100
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'date'
  weight = 10
