
languageCode = 'zh-cn'
DefaultContentLanguage = 'zh-cn'

title = "QingZhuo Hugo theme"

# baseURL = "https://eindex.github.io/qingzhuo"
# theme = "qingzhuo" # uncomment when you using as theme mode.

## Google Analytics
GoogleAnalytics = 'G-9WCVMESGP2'

paginate = 10 # default page size

hasCJKLanguage = true # CJK support
summaryLength = 70 # default summary length

# defaultContentLanguageInSubdir = true
# [languages]
# [languages.en]
# languageName = "English"
# weight = 2
# [languages.zh-cn]
# languageName = "简体中文"
# weight = 1

[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'

## RSS support default open
[outputs]
home = [ "RSS", "HTML"]

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"

## menus in navbar
[menu]
[[menu.navbar]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2

[[menu.navbar]]
identifier = "archive"
name = "Archive"
url = "/archive/"
weight = 1



[params]
# Time to start show outdate warning, 0 to close.
outdateingWarningDays = 30

## Baidu Analytics
baiduAnalytics = ''

## Microsoft clarify
microsoftClarity = ''

## deprecated: please using Site.GoogleAnalytics https://gohugo.io/templates/internal/#google-analytics
# googleAnalytics = '' 

## ICP infomation China mainland only
ICPNumbers = ''

## BuSuanZi Visit Counter
BuSuanZi = false


## support font awesome
[[params.socialaccount]]
link = 'https://github.com/eindex'
icon = 'fab fa-github'
label = 'Github'
[[params.socialaccount]]
link = 'https://twitter.com/eindex_li'
icon = 'fab fa-twitter'
label = 'Twitter'
[[params.socialaccount]]
link = 'https://t.me/eindex'
icon = 'fab fa-telegram'
label = 'Telegram'
[[params.socialaccount]]
link = 'mailto:eindex.me@outlook.com'
icon = 'fas fa-envelope'
label = 'Email'

## Giscus
[params.giscus]
repo = ""
repoId = ""
categoryId = ""


## Markup Configurations
[markup]

### Code Highlighting
[markup.highlight]
style = 'monokai'
tabWidth = 4

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

## hugo related logic
## https://gohugo.io/content-management/related/

[related]
  includeNewer = false
  threshold = 0
  toLower = false
[[related.indices]]
  name = 'tags'
  weight = 100
[[related.indices]]
  name = 'categories'
  weight = 100
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'date'
  weight = 10