baseURL = 'http://example.org/'
languageCode = 'cn'
theme = 'qingzhuo'
title = "EINDEX's Blog"

hasCJKLanguage = true
summaryLength = 100

[markup]
[markup.highlight]
style = 'monokai'
tabWidth = 4

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
