baseURL = 'https://eindex.me/'
languageCode = 'cn'
theme = 'qingzhuo'
title = "EINDEX's Blog"

hasCJKLanguage = true
summaryLength = 100

googleAnalytics = 'G-B4GVHJ5ND3'

[markup]
[markup.highlight]
style = 'monokai'
tabWidth = 4

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true


[outputs]
home = [ "RSS", "HTML"]

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"

[params]

outdateingWarningDays = 30

[params.giscus]
repo = "EINDEX/qingzhuo-hugo"
repoId = "R_kgDOGWb6Yg"
categoryId = "DIC_kwDOGWb6Ys4CAKn-"