version: "3.1"
services:
    web: 
        image: ghcr.io/eindex/qing-zhuo/web:${VERSION}
        ports:
            - 8888:80
    api:
        image: ghcr.io/eindex/qing-zhuo/api:${VERSION}
        environment:
            - DSN=${DSN}
        