version: "3.1"
services:
  blog:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./public:/etc/nginx/html:ro
      - ./blog.conf:/etc/nginx/nginx.conf:ro
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.blog.loadbalancer.server.port=80"
      - "traefik.http.routers.blog.entrypoints=web,websecure"
      - "traefik.http.routers.blog.tls.certresolver=eindex-me"
      - "traefik.http.routers.blog.rule=Host(`blogcdn.eindex.me`) || Host(`eindex.me`)"
      - "traefik.http.routers.blog.tls.options=default"

networks:
  traefik:
    external: true