version: 1
update_configs:
  # Keep package.json (& lockfiles) secure and up-to-date,
  # batching pull requests daily
  - package_manager: "javascript"
    directory: "/web"
    update_schedule: "live"
    target_branch: "dependabot"
    default_labels:
      - "dependencies"
      - "dependabot"
    default_assignees:
      - "EINDEX"
    
  - package_manager: "go:modules"
    directory: "/api"
    update_schedule: "daily"
    target_branch: "dependabot"
    default_labels:
      - "dependencies"
      - "dependabot"
    default_assignees:
      - "EINDEX"
    
   
